version: '3.8'
services:
  mongodb-service:
    image: mongo:5.0
    container_name: mongodb-service
    ports:
      - 27017:27017
    networks:
      - appnetwork
    volumes:
      - dbvol:/data/db
      - dbvolconfig:/data/configdb

  backend:
    image: groovyspleen/backend
    container_name: backend
    ports:
      - 5000:5000
    networks:
      - appnetwork
    depends_on:
      - mongodb-service

  frontend:
    image: groovyspleen/frontend
    container_name: frontend
    ports:
      - 3000:80
    networks:
      - appnetwork
    depends_on:
      - backend
    volumes:
      - dbvol:/path/to/frontend/volume

volumes:
  dbvol:
    driver: local
  dbvolconfig:
    driver: local

networks:
  appnetwork:
    driver: bridge
